Repository atoti/jdk4py, pull requests merged in 2020-08, with the labels that each got.

#5 Add jdk.crypto.ec module for TLS protocols
  jdk4py/version
  scripts/build_jdk.py
Labels: bug

#6 Add JMX support
  .github/workflows/deployment.yaml
  .github/workflows/test.yaml
  README.md
  jdk4py/__init__.py
  jdk4py/java_version
  jdk4py/java_version.txt
  jdk4py/lib_version.txt
  jdk4py/version
  scripts/build_jdk.py
  scripts/set_version.py
  scripts/upload.py
  setup.py
  tests/__init__.py
  tests/test_java_version.py
  tests/test_jdk4py.py
  tests/test_paths.py
  tests/test_run_jvm.py
Labels: enhancement

#7 Add missing version files to package_data
  .github/workflows/deployment.yaml
  .github/workflows/test.yaml
  .gitignore
  jdk4py/__init__.py
  jdk4py/lib_version.txt
  scripts/set_java_version.py
  scripts/set_version.py
  setup.py
  tests/test_jdk4py.py
Labels: bug, enhancement
