Repository atoti/jdk4py, pull requests merged in 2021-01, with the labels that each got.

#18 Update deployment actions to v2
  .github/workflows/deployment.yaml
Labels: dependencies

#15 Adding jdk.jfr module for flight recording
  scripts/build_jdk.py
Labels: missing-module

#21 Move to OpenJDK
  .github/workflows/deployment.yaml
  .github/workflows/test.yaml
  jdk4py/__init__.py
  jdk4py/java_version.txt
  jdk4py/lib_version.txt
  jdk4py/major_java_version.txt
  scripts/set_versions.py
  tests/test_jdk4py.py
Labels: dependencies

#22 Check packaging, add missing file, add info about versioning
  .github/workflows/test.yaml
  README.md
  setup.py
Labels: CI, documentation
